from fileinput import filename
import json
import pickle

def writeToPickle(fileName, contents):
    pickle.dump(contents, open(fileName, 'wb'))

def readFromPickle(fileName):
    out = pickle.load(open('test.pkl', 'rb'))
    return out

event = {'resource': '/packages/correlation', 'path': '/packages/correlation', 'httpMethod': 'POST', 'headers': {'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate, br', 'Cache-Control': 'no-cache', 'CloudFront-Forwarded-Proto': 'https', 'CloudFront-Is-Desktop-Viewer': 'true', 'CloudFront-Is-Mobile-Viewer': 'false', 'CloudFront-Is-SmartTV-Viewer': 'false', 'CloudFront-Is-Tablet-Viewer': 'false', 'CloudFront-Viewer-ASN': '14618', 'CloudFront-Viewer-Country': 'US', 'Content-Type': 'application/json', 'Host': 'jpbcmpeprl.execute-api.us-west-1.amazonaws.com', 'Postman-Token': '7f5a0f72-63ca-4552-a907-c924c8a8266d', 'User-Agent': 'PostmanRuntime/7.29.2', 'Via': '1.1 4ce044af637284f41cd11c7043e8eaaa.cloudfront.net (CloudFront)', 'X-Amz-Cf-Id': 'pAJSiyWt60AflRLgIxsO1bpzCg2paF-QMMNSF6XnYWx2dCnn1ArI1g==', 'X-Amzn-Trace-Id': 'Root=1-634b7e31-616c493d47b9178732d26496', 'X-Forwarded-For': '54.86.50.139, 15.158.41.211', 'X-Forwarded-Port': '443', 'X-Forwarded-Proto': 'https'}, 'multiValueHeaders': {'Accept': ['*/*'], 'Accept-Encoding': ['gzip, deflate, br'], 'Cache-Control': ['no-cache'], 'CloudFront-Forwarded-Proto': ['https'], 'CloudFront-Is-Desktop-Viewer': ['true'], 'CloudFront-Is-Mobile-Viewer': ['false'], 'CloudFront-Is-SmartTV-Viewer': ['false'], 'CloudFront-Is-Tablet-Viewer': ['false'], 'CloudFront-Viewer-ASN': ['14618'], 'CloudFront-Viewer-Country': ['US'], 'Content-Type': ['application/json'], 'Host': ['jpbcmpeprl.execute-api.us-west-1.amazonaws.com'], 'Postman-Token': ['7f5a0f72-63ca-4552-a907-c924c8a8266d'], 'User-Agent': ['PostmanRuntime/7.29.2'], 'Via': ['1.1 4ce044af637284f41cd11c7043e8eaaa.cloudfront.net (CloudFront)'], 'X-Amz-Cf-Id': ['pAJSiyWt60AflRLgIxsO1bpzCg2paF-QMMNSF6XnYWx2dCnn1ArI1g=='], 'X-Amzn-Trace-Id': ['Root=1-634b7e31-616c493d47b9178732d26496'], 'X-Forwarded-For': ['54.86.50.139, 15.158.41.211'], 'X-Forwarded-Port': ['443'], 'X-Forwarded-Proto': ['https']}, 'queryStringParameters': None, 'multiValueQueryStringParameters': None, 'pathParameters': None, 'stageVariables': None, 'requestContext': {'resourceId': '8ded7w', 'resourcePath': '/packages/correlation', 'httpMethod': 'POST', 'extendedRequestId': 'aFCnwGWSyK4FjVg=', 'requestTime': '16/Oct/2022:03:44:49 +0000', 'path': '/Prod/packages/correlation', 'accountId': '080635268317', 'protocol': 'HTTP/1.1', 'stage': 'Prod', 'domainPrefix': 'jpbcmpeprl', 'requestTimeEpoch': 1665891889407, 'requestId': '357e919f-6873-4500-a6e7-44237bff2b65', 'identity': {'cognitoIdentityPoolId': None, 'accountId': None, 'cognitoIdentityId': None, 'caller': None, 'sourceIp': '54.86.50.139', 'principalOrgId': None, 'accessKey': None, 'cognitoAuthenticationType': None, 'cognitoAuthenticationProvider': None, 'userArn': None, 'userAgent': 'PostmanRuntime/7.29.2', 'user': None}, 'domainName': 'jpbcmpeprl.execute-api.us-west-1.amazonaws.com', 'apiId': 'jpbcmpeprl'}, 'body': '{"payload": "Tobias"}', 'isBase64Encoded': False}

res = json.loads(event.get("body"))
print(res.get("payload"))